### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by bsipos** [benedictpaten/marginPhase#6]
Hello,

I have followed the installation instructions and got this error message when compiling:

```
[  1%] Building C object CMakeFiles/hts.dir/externalTools/htslib/hfile_s3.c.o
/home/OXFORDNANOLABS/bsipos/soft/marginPhase/externalTools/htslib/hfile_s3.c:70:2: error: #error No HMAC() routine found by configure
 #error No HMAC() routine found by configure
  ^
/home/OXFORDNANOLABS/bsipos/soft/marginPhase/externalTools/htslib/hfile_s3.c: In function ‘s3_rewrite’:
/home/OXFORDNANOLABS/bsipos/soft/marginPhase/externalTools/htslib/hfile_s3.c:335:30: error: ‘DIGEST_BUFSIZ’ undeclared (first use in this function)
         unsigned char digest[DIGEST_BUFSIZ];
                              ^
/home/OXFORDNANOLABS/bsipos/soft/marginPhase/externalTools/htslib/hfile_s3.c:335:30: note: each undeclared identifier is reported only once for each function it appears in
/home/OXFORDNANOLABS/bsipos/soft/marginPhase/externalTools/htslib/hfile_s3.c:336:9: warning: implicit declaration of function ‘s3_sign’ [-Wimplicit-function-declaration]
         size_t digest_len = s3_sign(digest, &secret, &message);
         ^
make[2]: *** [CMakeFiles/hts.dir/externalTools/htslib/hfile_s3.c.o] Error 1
make[1]: *** [CMakeFiles/hts.dir/all] Error 2
make: *** [all] Error 2
```
Are there any unstated dependencies which can cause this?

Regards,
Botond

**Comment by tpesout** [comment]
Botond,

I've seen this before and I think this solves it (at least with the Ubuntu package manager):

apt-get -y install git make gcc bzip2 lzma-dev zlib1g-dev libcurl4-openssl-dev libcrypto++-dev libpthread-stubs0-dev g++ wget libbz2-dev liblzma-dev autoconf

I believe you'll need to rerun this from the htslib directory:
autoconf ; autoheader ; ./configure

I've updated the README with this info.  Please let me know if this works!

**Comment by bsipos** [comment]
I have switched to Ubuntu 16.04 and installed the packages as instructed. Unfortunately I still get the same compilation error.

**Comment by tpesout** [comment]
I updated the README again after trying the install procedure on a fresh box.  I suggest trying a fresh install with the updated instructions.  The command to setup htslib had a typo ("cd htsLib" should have been "cd htslib").  Maybe run each of those commands separately?  If this fails, please send me a script of the commands you ran and the output so that I can debug this.
Also note that cmake 3.7 is required (I don't think this is your issue) and I added a short script to install that.

**Comment by bsipos** [comment]
So now I am following exactly the instructions from the REAMDE, including the installation of the specific cmake version.
Now I get this error in the cmake step:

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:224 (message):
  Couldn't find the 'crypto' library

-- Configuring incomplete, errors occurred!
```
I find this strange as libcrypto++-dev is definitely installed.

**Comment by tpesout** [comment]
Alright, I've done some more digging and it looks like libgcrypt11-dev (which gets included with libcurl4-openssl-dev) may be what's required (and libcrypto++-dev is not required).  Can you ensure that is installed?  

For reference, most of these requirements are from htslib and I discovered them while building the marginPhase docker image.  If the above doesn't work, I recommend trying to build the docker image by executing 'make' in the marginPhase/toil/docker directory to enable you to work in the meantime.

**Comment by bsipos** [comment]
Managed to compile marginPhase, it seems that it needed libssl-dev to be installed.

**Comment by tpesout** [comment]
Glad it worked!
